- name: Install firewall bouncer
  ansible.builtin.apt:
    name: crowdsec-firewall-bouncer-nftables
    state: present
    update_cache: true

- name: Create API key for Crowdsec Local API to be used in Traefik bouncer plugin
  ansible.builtin.shell:
    cmd: "cscli bouncers add crowdsecTraefikBouncer -o raw > {{ docker.base_dir }}/infrastructure/traefik_bouncer_api_key.txt"
    creates: "{{ docker.base_dir }}/infrastructure/traefik_bouncer_api_key.txt"
  tags: console
