- name: Install and configure services for development and software engineering
  # Contains gitea, jenkins, ...
  hosts: schoolservers
  become: true
  remote_user: "{{ admin.username }}"
  tags: development
  roles:
    - role: gitea
      tags: programming
    - role: forgejo
      tags: programming
    - role: jenkins
      tags: programming
    - role: kanboard
      tags: projectmanagement
    # - role: hesk
    #  tags: projectmanagement
