- name: Install and configure services for development and software engineering
  # Contains gitea, jenkins, ...
  hosts: schoolservers
  become: true
  remote_user: "{{ admin.username }}"
  tags: development
  roles:
    - gitea
    - jenkins
    - kanboard
    - hesk
