- name: Install and configure basic services
  # Basic services contains reverse proxy, container management, status monitoring, automatic container updates
  hosts: schoolservers
  become: true
  remote_user: "{{ admin.name }}"
  roles:
    - docker
    - infrastructure
    - role: authentik
      tags:
        - security
    - role: firewall
      tags:
        - security
    - role: monitoring
      tags:
        - monitoring
    - role: crowdsec
      tags:
        - security
