- name: Install and configure tools for collaboration and education
  # Contains etherpad, hedgedocs
  hosts: schoolservers
  become: true
  remote_user: "{{ admin.name }}"
  tags: tools
  roles:
    - etherpad
    - hedgedoc
    - onlyoffice
    - homepage
