- name: Install and configure tools for collaboration and education
  # Contains etherpad, hedgedocs
  hosts: schoolservers
  become: true
  remote_user: "{{ admin.username }}"
  tags: tools
  roles:
    - role: etherpad
      tags: editors
    - role: hedgedoc
      tags: editors
    - role: onlyoffice
      tags: misc
    - role: homepage
      tags: misc
