- name: Output all classes for which to start a Hesk instance
  ansible.builtin.debug:
    msg: "Creating Hesk instance at {{ docker.base_dir }}/hesk-{{ item | lower }}"
  loop: "{{ hesk_class_list }}"

- name: Install and configure a Hesk instance for each class
  ansible.builtin.include_tasks: install.yml
  vars:
    hesk_instance_base_dir: "{{ docker.base_dir }}/hesk-{{ item | lower }}"
    hesk_instance_subdomain: "hesk-{{ item | lower }}"
  loop: "{{ hesk_class_list }}"
