- name: Add SSH public key
  ansible.posix.authorized_key:
    user: "{{ admin.username }}"
    key: "{{ admin.key }}"

- name: Disable root SSH login
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
    validate: /usr/sbin/sshd -T -f %s
  notify:
    - Restart sshd

- name: Only allow SSH key authentication
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regex: "^AuthenticationMethods"
    line: "AuthenticationMethods publickey"
    state: present
    validate: /usr/sbin/sshd -T -f %s
  notify:
    - Restart sshd

- name: Disable SSH password authentication
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    validate: /usr/sbin/sshd -T -f %s
  notify:
    - Restart sshd
