- name: Install apt packages
  become: true
  apt:
    update_cache: yes
    name: "{{ basic_packages }}"
    state: present

- name: Upgrade all apt packages
  become: true
  apt:
    force_apt_get: yes
    upgrade: dist

- name: All packages installed.
  debug:
    msg: Packages have been successfully installed

- name: Copy script to update manually
  become: true
  ansible.builtin.copy:
    src: files/update.sh
    dest: /root/update.sh
