- name: Install apt packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: "{{ system_basic_packages }}"
    state: present

- name: Upgrade all apt packages
  become: true
  ansible.builtin.apt:
    force_apt_get: true
    upgrade: dist

- name: All packages installed.
  ansible.builtin.debug:
    msg: Packages have been successfully installed

- name: Create directory for scripts
  ansible.builtin.file:
    path: "{{ scripts.base_dir }}"
    state: directory
    mode: "0644"

- name: Copy script to update manually
  become: true
  ansible.builtin.copy:
    src: files/update.sh
    dest: "{{ scripts.base_dir }}/update.sh"
    mode: "0755"
